from LinkedList import LinkedList

my_ll = LinkedList(1)
my_ll.append(2)
my_ll.append(3)
my_ll.append(4)
my_ll.append(5)
my_ll.traverse()
item = my_ll.pop()
while item is not None:
    print(f'Value popped is: {item.value}')
    print('Linked list after pop operation: ', end="")
    my_ll.traverse()
    item = my_ll.pop()
print('Linked list is now empty')
my_ll.prepend(1)
my_ll.traverse()
my_ll.prepend(0)
my_ll.traverse()
my_ll.prepend(-1)
my_ll.traverse()
my_ll.append(2)
my_ll.traverse()
item = my_ll.pop_first()
print(f'Value of the node that was popped is: {item.value}')
my_ll.traverse()
print(f'Value of node in first index is: {my_ll.get(1).value}')
my_ll.traverse()
my_ll.set_value(1, 4)
my_ll.traverse()
my_ll.insert(0, -1)
my_ll.traverse()
my_ll.insert(2, 1)
my_ll.traverse()
my_ll.insert(3,2)
my_ll.traverse()
my_ll.insert(4, 3)
my_ll.traverse()
my_ll.remove(0)
my_ll.traverse()
my_ll.remove(5)
my_ll.traverse()
my_ll.insert(3, 5)
my_ll.traverse()
my_ll.remove(3)
my_ll.traverse()
my_ll.reverse()
my_ll.traverse()